[build]
command = "npm ci && npm run build"
publish = "dist"

[build.environment]
# Remove or override NODE_ENV.  For example, set it to "development":
NODE_ENV = "development"

# Keep your existing flags if you want to allow peer-deps
NPM_FLAGS = "--legacy-peer-deps"
node_version = "16"
