[build]
command = "npm ci && npm run build"
publish = "dist"

[build.environment]
NODE_ENV = "development"
NPM_FLAGS = "--legacy-peer-deps"
node_version = "16"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
