[build]
command = "npm run build"  # Ensure this matches your Vue build command
publish = "dist"          # Vue apps typically output to the "dist" directory

[build.environment]
NODE_ENV = "production"
